include ./theme.conf

# BEGIN_KITTY_THEME
# Everforest Dark Soft
include current-theme.conf
# END_KITTY_THEME
map ctrl+shift+d kitten themes --reload-in=all Everforest Dark Soft
map ctrl+shift+l kitten themes --reload-in=all Everforest Light Soft

# FONT
font_size 14.0

# Open New Pane Keybindings
allow_remote_control yes
default_layout splits
enabled_layouts splits

# Unmap built-in zoom first
map ctrl+equal no_op
map ctrl+shift+equal no_op

# Splits — right = vsplit, below = hsplit
map ctrl+equal launch --location=vsplit
map ctrl+\ launch --location=hsplit

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down
